[package]
name = "bevy_flowfield_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
bevy-inspector-egui = "0.9.0"
ncollide2d = "0.33.0"
